package zio.sql

import zio.test._
import zio.Scope

object PluralizeSpec extends ZIOSpecDefault {

  def spec: Spec[Environment with TestEnvironment with Scope, Any] =
    suite("correctly pluralize")(
      test("pluralize 1") {
        assertTrue(Pluralize.pluralize("louse") == "lice") &&
        assertTrue(Pluralize.pluralize("accomplice") == "accomplices") &&
        assertTrue(Pluralize.pluralize("pokemon") == "pokemon") &&
        assertTrue(Pluralize.pluralize("courthouse") == "courthouses") &&
        assertTrue(Pluralize.pluralize("pokémon") == "pokémon") &&
        assertTrue(Pluralize.pluralize("tomato") == "tomatoes") &&
        assertTrue(Pluralize.pluralize("person") == "people") &&
        assertTrue(Pluralize.pluralize("people") == "people") &&
        assertTrue(Pluralize.pluralize("origins") == "origins") &&
        assertTrue(Pluralize.pluralize("origin") == "origins") &&
        assertTrue(Pluralize.pluralize("man") == "men") &&
        assertTrue(Pluralize.pluralize("address") == "addresses") &&
        assertTrue(Pluralize.pluralize("starfish") == ("starfish")) &&
        assertTrue(Pluralize.pluralize("person") == "people") &&
        assertTrue(Pluralize.pluralize("seraph") == "seraphim") &&
        assertTrue(Pluralize.pluralize("knife") == "knives") &&
        assertTrue(Pluralize.pluralize("hoof") == "hooves") &&
        assertTrue(Pluralize.pluralize("firmware") == ("firmware")) &&
        assertTrue(Pluralize.pluralize("fish") == ("fish")) &&
        assertTrue(Pluralize.pluralize("media") == ("media")) &&
        assertTrue(Pluralize.pluralize("moose") == ("moose")) &&
        assertTrue(Pluralize.pluralize("police") == ("police")) &&
        assertTrue(Pluralize.pluralize("sheep") == ("sheep")) &&
        assertTrue(Pluralize.pluralize("series") == ("series")) &&
        assertTrue(Pluralize.pluralize("agenda") == ("agenda")) &&
        assertTrue(Pluralize.pluralize("news") == ("news")) &&
        assertTrue(Pluralize.pluralize("reindeer") == ("reindeer")) &&
        assertTrue(Pluralize.pluralize("smallpox") == ("smallpox")) &&
        assertTrue(Pluralize.pluralize("tennis") == ("tennis")) &&
        assertTrue(Pluralize.pluralize("chickenpox") == ("chickenpox")) &&
        assertTrue(Pluralize.pluralize("shambles") == ("shambles")) &&
        assertTrue(Pluralize.pluralize("garbage") == ("garbage")) &&
        assertTrue(Pluralize.pluralize("you") == ("you")) &&
        assertTrue(Pluralize.pluralize("wildlife") == ("wildlife")) &&
        assertTrue(Pluralize.pluralize("Staff") == ("Staff")) &&
        assertTrue(Pluralize.pluralize("STAFF") == ("STAFF")) &&
        assertTrue(Pluralize.pluralize("turquois") == ("turquois")) &&
        assertTrue(Pluralize.pluralize("carnivorous") == ("carnivorous")) &&
        assertTrue(Pluralize.pluralize("only") == ("only")) &&
        assertTrue(Pluralize.pluralize("aircraft") == ("aircraft")) &&
        assertTrue(Pluralize.pluralize("this") == "these") &&
        assertTrue(Pluralize.pluralize("that") == "those") &&
        assertTrue(Pluralize.pluralize("is") == "are") &&
        assertTrue(Pluralize.pluralize("superman") == "supermen") &&
        assertTrue(Pluralize.pluralize("ox") == "oxen") &&
        assertTrue(Pluralize.pluralize("bus") == "buses") &&
        assertTrue(Pluralize.pluralize("airbus") == "airbuses") &&
        assertTrue(Pluralize.pluralize("railbus") == "railbuses") &&
        assertTrue(Pluralize.pluralize("wife") == "wives") &&
        assertTrue(Pluralize.pluralize("guest") == "guests") &&
        assertTrue(Pluralize.pluralize("thing") == "things") &&
        assertTrue(Pluralize.pluralize("mess") == "messes") &&
        assertTrue(Pluralize.pluralize("guess") == "guesses") &&
        assertTrue(Pluralize.pluralize("person") == "people") &&
        assertTrue(Pluralize.pluralize("meteor") == "meteors") &&
        assertTrue(Pluralize.pluralize("chateau") == "chateaus") &&
        assertTrue(Pluralize.pluralize("lap") == "laps") &&
        assertTrue(Pluralize.pluralize("cough") == "coughs") &&
        assertTrue(Pluralize.pluralize("death") == "deaths") &&
        assertTrue(Pluralize.pluralize("coach") == "coaches") &&
        assertTrue(Pluralize.pluralize("boy") == "boys") &&
        assertTrue(Pluralize.pluralize("toy") == "toys") &&
        assertTrue(Pluralize.pluralize("guy") == "guys") &&
        assertTrue(Pluralize.pluralize("girl") == "girls") &&
        assertTrue(Pluralize.pluralize("chair") == "chairs") &&
        assertTrue(Pluralize.pluralize("toe") == "toes")
      },
      test("pluralize 2") {
        assertTrue(Pluralize.pluralize("tiptoe") == "tiptoes") &&
        assertTrue(Pluralize.pluralize("tomato") == "tomatoes") &&
        assertTrue(Pluralize.pluralize("potato") == "potatoes") &&
        assertTrue(Pluralize.pluralize("tornado") == "tornadoes") &&
        assertTrue(Pluralize.pluralize("torpedo") == "torpedoes") &&
        assertTrue(Pluralize.pluralize("hero") == "heroes") &&
        assertTrue(Pluralize.pluralize("superhero") == "superheroes") &&
        assertTrue(Pluralize.pluralize("volcano") == "volcanoes") &&
        assertTrue(Pluralize.pluralize("canto") == "cantos") &&
        assertTrue(Pluralize.pluralize("hetero") == "heteros") &&
        assertTrue(Pluralize.pluralize("photo") == "photos") &&
        assertTrue(Pluralize.pluralize("portico") == "porticos") &&
        assertTrue(Pluralize.pluralize("quarto") == "quartos") &&
        assertTrue(Pluralize.pluralize("kimono") == "kimonos") &&
        assertTrue(Pluralize.pluralize("albino") == "albinos") &&
        assertTrue(Pluralize.pluralize("cherry") == "cherries") &&
        assertTrue(Pluralize.pluralize("piano") == "pianos") &&
        assertTrue(Pluralize.pluralize("pro") == "pros") &&
        assertTrue(Pluralize.pluralize("combo") == "combos") &&
        assertTrue(Pluralize.pluralize("turbo") == "turbos") &&
        assertTrue(Pluralize.pluralize("bar") == "bars") &&
        assertTrue(Pluralize.pluralize("crowbar") == "crowbars") &&
        assertTrue(Pluralize.pluralize("van") == "vans") &&
        assertTrue(Pluralize.pluralize("tobacco") == "tobaccos") &&
        assertTrue(Pluralize.pluralize("afficionado") == "afficionados") &&
        assertTrue(Pluralize.pluralize("monkey") == "monkeys") &&
        assertTrue(Pluralize.pluralize("neutrino") == "neutrinos") &&
        assertTrue(Pluralize.pluralize("rhino") == "rhinos") &&
        assertTrue(Pluralize.pluralize("steno") == "stenos") &&
        assertTrue(Pluralize.pluralize("latino") == "latinos") &&
        assertTrue(Pluralize.pluralize("casino") == "casinos") &&
        assertTrue(Pluralize.pluralize("avocado") == "avocados") &&
        assertTrue(Pluralize.pluralize("commando") == "commandos") &&
        assertTrue(Pluralize.pluralize("tuxedo") == "tuxedos") &&
        assertTrue(Pluralize.pluralize("speedo") == "speedos") &&
        assertTrue(Pluralize.pluralize("dingo") == "dingoes") &&
        assertTrue(Pluralize.pluralize("echo") == "echoes") &&
        assertTrue(Pluralize.pluralize("nacho") == "nachos") &&
        assertTrue(Pluralize.pluralize("motto") == "mottos") &&
        assertTrue(Pluralize.pluralize("psycho") == "psychos") &&
        assertTrue(Pluralize.pluralize("poncho") == "ponchos") &&
        assertTrue(Pluralize.pluralize("pass") == "passes") &&
        assertTrue(Pluralize.pluralize("ghetto") == "ghettos") &&
        assertTrue(Pluralize.pluralize("mango") == "mangos") &&
        assertTrue(Pluralize.pluralize("lady") == "ladies") &&
        assertTrue(Pluralize.pluralize("bath") == "baths") &&
        assertTrue(Pluralize.pluralize("professional") == "professionals") &&
        assertTrue(Pluralize.pluralize("dwarf") == "dwarves") &&
        assertTrue(Pluralize.pluralize("encyclopedia") == "encyclopedias") &&
        assertTrue(Pluralize.pluralize("roof") == "roofs") &&
        assertTrue(Pluralize.pluralize("woman") == "women") &&
        assertTrue(Pluralize.pluralize("formula") == "formulas") &&
        assertTrue(Pluralize.pluralize("polyhedron") == "polyhedra") &&
        assertTrue(Pluralize.pluralize("index") == "indices") &&
        assertTrue(Pluralize.pluralize("matrix") == "matrices") &&
        assertTrue(Pluralize.pluralize("vertex") == "vertices") &&
        assertTrue(Pluralize.pluralize("axe") == "axes") &&
        assertTrue(Pluralize.pluralize("pickaxe") == "pickaxes")
      },
      test("pluralize 3") {
        assertTrue(Pluralize.pluralize("crisis") == "crises") &&
        assertTrue(Pluralize.pluralize("criterion") == "criteria") &&
        assertTrue(Pluralize.pluralize("phenomenon") == "phenomena") &&
        assertTrue(Pluralize.pluralize("addendum") == "addenda") &&
        assertTrue(Pluralize.pluralize("datum") == "data") &&
        assertTrue(Pluralize.pluralize("forum") == "forums") &&
        assertTrue(Pluralize.pluralize("millennium") == "millennia") &&
        assertTrue(Pluralize.pluralize("alumnus") == "alumni") &&
        assertTrue(Pluralize.pluralize("medium") == "mediums") &&
        assertTrue(Pluralize.pluralize("census") == "censuses") &&
        assertTrue(Pluralize.pluralize("genus") == "genera") &&
        assertTrue(Pluralize.pluralize("dogma") == "dogmata") &&
        assertTrue(Pluralize.pluralize("life") == "lives") &&
        assertTrue(Pluralize.pluralize("hive") == "hives") &&
        assertTrue(Pluralize.pluralize("self") == "selves") &&
        assertTrue(Pluralize.pluralize("kiss") == "kisses") &&
        assertTrue(Pluralize.pluralize("dish") == "dishes") &&
        assertTrue(Pluralize.pluralize("human") == "humans") &&
        assertTrue(Pluralize.pluralize("knife") == "knives") &&
        assertTrue(Pluralize.pluralize("phase") == "phases") &&
        assertTrue(Pluralize.pluralize("judge") == "judges") &&
        assertTrue(Pluralize.pluralize("class") == "classes") &&
        assertTrue(Pluralize.pluralize("witch") == "witches") &&
        assertTrue(Pluralize.pluralize("church") == "churches") &&
        assertTrue(Pluralize.pluralize("massage") == "massages") &&
        assertTrue(Pluralize.pluralize("prospectus") == "prospectuses") &&
        assertTrue(Pluralize.pluralize("syllabus") == "syllabi") &&
        assertTrue(Pluralize.pluralize("viscus") == "viscera") &&
        assertTrue(Pluralize.pluralize("cactus") == "cacti") &&
        assertTrue(Pluralize.pluralize("hippopotamus") == "hippopotamuses") &&
        assertTrue(Pluralize.pluralize("octopus") == "octopuses") &&
        assertTrue(Pluralize.pluralize("platypus") == "platypuses") &&
        assertTrue(Pluralize.pluralize("kangaroo") == "kangaroos") &&
        assertTrue(Pluralize.pluralize("atlas") == "atlases") &&
        assertTrue(Pluralize.pluralize("stigma") == "stigmata") &&
        assertTrue(Pluralize.pluralize("schema") == "schemata") &&
        assertTrue(Pluralize.pluralize("phenomenon") == "phenomena") &&
        assertTrue(Pluralize.pluralize("diagnosis") == "diagnoses") &&
        assertTrue(Pluralize.pluralize("mongoose") == "mongooses") &&
        assertTrue(Pluralize.pluralize("mouse") == "mice") &&
        assertTrue(Pluralize.pluralize("liturgist") == "liturgists") &&
        assertTrue(Pluralize.pluralize("box") == "boxes") &&
        assertTrue(Pluralize.pluralize("gas") == "gases") &&
        assertTrue(Pluralize.pluralize("chief") == "chiefs") &&
        assertTrue(Pluralize.pluralize("quiz") == "quizzes") &&
        assertTrue(Pluralize.pluralize("child") == "children") &&
        assertTrue(Pluralize.pluralize("shelf") == "shelves") &&
        assertTrue(Pluralize.pluralize("fizz") == "fizzes") &&
        assertTrue(Pluralize.pluralize("tooth") == "teeth") &&
        assertTrue(Pluralize.pluralize("thief") == "thieves") &&
        assertTrue(Pluralize.pluralize("day") == "days") &&
        assertTrue(Pluralize.pluralize("loaf") == "loaves") &&
        assertTrue(Pluralize.pluralize("fix") == "fixes") &&
        assertTrue(Pluralize.pluralize("spy") == "spies") &&
        assertTrue(Pluralize.pluralize("vertebra") == "vertebrae") &&
        assertTrue(Pluralize.pluralize("clock") == "clocks") &&
        assertTrue(Pluralize.pluralize("lap") == "laps") &&
        assertTrue(Pluralize.pluralize("cuff") == "cuffs") &&
        assertTrue(Pluralize.pluralize("leaf") == "leaves") &&
        assertTrue(Pluralize.pluralize("calf") == "calves") &&
        assertTrue(Pluralize.pluralize("moth") == "moths") &&
        assertTrue(Pluralize.pluralize("mouth") == "mouths") &&
        assertTrue(Pluralize.pluralize("house") == "houses") &&
        assertTrue(Pluralize.pluralize("proof") == "proofs") &&
        assertTrue(Pluralize.pluralize("hoof") == "hooves") &&
        assertTrue(Pluralize.pluralize("elf") == "elves") &&
        assertTrue(Pluralize.pluralize("turf") == "turfs") &&
        assertTrue(Pluralize.pluralize("craft") == "crafts") &&
        assertTrue(Pluralize.pluralize("die") == "dice") &&
        assertTrue(Pluralize.pluralize("penny") == "pennies") &&
        assertTrue(Pluralize.pluralize("campus") == "campuses") &&
        assertTrue(Pluralize.pluralize("virus") == "viri") &&
        assertTrue(Pluralize.pluralize("iris") == "irises") &&
        assertTrue(Pluralize.pluralize("bureau") == "bureaus") &&
        assertTrue(Pluralize.pluralize("kiwi") == "kiwis") &&
        assertTrue(Pluralize.pluralize("wiki") == "wikis") &&
        assertTrue(Pluralize.pluralize("igloo") == "igloos") &&
        assertTrue(Pluralize.pluralize("ninja") == "ninjas") &&
        assertTrue(Pluralize.pluralize("pizza") == "pizzas") &&
        assertTrue(Pluralize.pluralize("kayak") == "kayaks") &&
        assertTrue(Pluralize.pluralize("canoe") == "canoes") &&
        assertTrue(Pluralize.pluralize("tiding") == "tidings") &&
        assertTrue(Pluralize.pluralize("pea") == "peas") &&
        assertTrue(Pluralize.pluralize("drive") == "drives") &&
        assertTrue(Pluralize.pluralize("nose") == "noses")
      },
      test("pluralize 4") {
        assertTrue(Pluralize.pluralize("movie") == "movies") &&
        assertTrue(Pluralize.pluralize("status") == "statuses") &&
        assertTrue(Pluralize.pluralize("alias") == "aliases") &&
        assertTrue(Pluralize.pluralize("memorandum") == "memorandums") &&
        assertTrue(Pluralize.pluralize("language") == "languages") &&
        assertTrue(Pluralize.pluralize("plural") == "plurals") &&
        assertTrue(Pluralize.pluralize("word") == "words") &&
        assertTrue(Pluralize.pluralize("multiple") == "multiples") &&
        assertTrue(Pluralize.pluralize("reward") == "rewards") &&
        assertTrue(Pluralize.pluralize("sandwich") == "sandwiches") &&
        assertTrue(Pluralize.pluralize("subway") == "subways") &&
        assertTrue(Pluralize.pluralize("direction") == "directions") &&
        assertTrue(Pluralize.pluralize("land") == "lands") &&
        assertTrue(Pluralize.pluralize("row") == "rows") &&
        assertTrue(Pluralize.pluralize("grow") == "grows") &&
        assertTrue(Pluralize.pluralize("flow") == "flows") &&
        assertTrue(Pluralize.pluralize("rose") == "roses") &&
        assertTrue(Pluralize.pluralize("raise") == "raises") &&
        assertTrue(Pluralize.pluralize("friend") == "friends") &&
        assertTrue(Pluralize.pluralize("follower") == "followers") &&
        assertTrue(Pluralize.pluralize("male") == "males") &&
        assertTrue(Pluralize.pluralize("nail") == "nails") &&
        assertTrue(Pluralize.pluralize("sex") == "sexes") &&
        assertTrue(Pluralize.pluralize("tape") == "tapes") &&
        assertTrue(Pluralize.pluralize("ruler") == "rulers") &&
        assertTrue(Pluralize.pluralize("king") == "kings") &&
        assertTrue(Pluralize.pluralize("queen") == "queens") &&
        assertTrue(Pluralize.pluralize("zero") == "zeros") &&
        assertTrue(Pluralize.pluralize("quest") == "quests") &&
        assertTrue(Pluralize.pluralize("goose") == "geese") &&
        assertTrue(Pluralize.pluralize("foot") == "feet") &&
        assertTrue(Pluralize.pluralize("ex") == "exes") &&
        assertTrue(Pluralize.pluralize("reflex") == "reflexes") &&
        assertTrue(Pluralize.pluralize("heat") == "heats") &&
        assertTrue(Pluralize.pluralize("train") == "trains") &&
        assertTrue(Pluralize.pluralize("test") == "tests") &&
        assertTrue(Pluralize.pluralize("pie") == "pies") &&
        assertTrue(Pluralize.pluralize("fly") == "flies") &&
        assertTrue(Pluralize.pluralize("eye") == "eyes") &&
        assertTrue(Pluralize.pluralize("lie") == "lies") &&
        assertTrue(Pluralize.pluralize("node") == "nodes") &&
        assertTrue(Pluralize.pluralize("trade") == "trades") &&
        assertTrue(Pluralize.pluralize("chinese") == "chinese") &&
        assertTrue(Pluralize.pluralize("please") == "pleases") &&
        assertTrue(Pluralize.pluralize("japanese") == "japanese") &&
        assertTrue(Pluralize.pluralize("regex") == "regexes") &&
        assertTrue(Pluralize.pluralize("license") == "licenses") &&
        assertTrue(Pluralize.pluralize("zebra") == "zebras") &&
        assertTrue(Pluralize.pluralize("general") == "generals") &&
        assertTrue(Pluralize.pluralize("corps") == "corps") &&
        assertTrue(Pluralize.pluralize("pliers") == "pliers") &&
        assertTrue(Pluralize.pluralize("flyer") == "flyers") &&
        assertTrue(Pluralize.pluralize("scissors") == "scissors") &&
        assertTrue(Pluralize.pluralize("fireman") == "firemen") &&
        assertTrue(Pluralize.pluralize("chirp") == "chirps") &&
        assertTrue(Pluralize.pluralize("harp") == "harps") &&
        assertTrue(Pluralize.pluralize("corpse") == "corpses") &&
        assertTrue(Pluralize.pluralize("dye") == "dyes") &&
        assertTrue(Pluralize.pluralize("move") == "moves") &&
        assertTrue(Pluralize.pluralize("zombie") == "zombies") &&
        assertTrue(Pluralize.pluralize("variety") == "varieties") &&
        assertTrue(Pluralize.pluralize("talkie") == "talkies") &&
        assertTrue(Pluralize.pluralize("walkie-talkie") == "walkie-talkies") &&
        assertTrue(Pluralize.pluralize("groupie") == "groupies") &&
        assertTrue(Pluralize.pluralize("goonie") == "goonies") &&
        assertTrue(Pluralize.pluralize("lassie") == "lassies") &&
        assertTrue(Pluralize.pluralize("genie") == "genies") &&
        assertTrue(Pluralize.pluralize("foodie") == "foodies") &&
        assertTrue(Pluralize.pluralize("faerie") == "faeries") &&
        assertTrue(Pluralize.pluralize("collie") == "collies") &&
        assertTrue(Pluralize.pluralize("obloquy") == "obloquies") &&
        assertTrue(Pluralize.pluralize("looey") == "looies") &&
        assertTrue(Pluralize.pluralize("osprey") == "ospreys") &&
        assertTrue(Pluralize.pluralize("cover") == "covers") &&
        assertTrue(Pluralize.pluralize("tie") == "ties") &&
        assertTrue(Pluralize.pluralize("groove") == "grooves") &&
        assertTrue(Pluralize.pluralize("bee") == "bees") &&
        assertTrue(Pluralize.pluralize("ave") == "aves") &&
        assertTrue(Pluralize.pluralize("wave") == "waves") &&
        assertTrue(Pluralize.pluralize("wolf") == "wolves") &&
        assertTrue(Pluralize.pluralize("airwave") == "airwaves") &&
        assertTrue(Pluralize.pluralize("archive") == "archives") &&
        assertTrue(Pluralize.pluralize("arch") == "arches") &&
        assertTrue(Pluralize.pluralize("dive") == "dives") &&
        assertTrue(Pluralize.pluralize("aftershave") == "aftershaves") &&
        assertTrue(Pluralize.pluralize("cave") == "caves") &&
        assertTrue(Pluralize.pluralize("grave") == "graves") &&
        assertTrue(Pluralize.pluralize("gift") == "gifts") &&
        assertTrue(Pluralize.pluralize("nerve") == "nerves") &&
        assertTrue(Pluralize.pluralize("nerd") == "nerds") &&
        assertTrue(Pluralize.pluralize("carve") == "carves") &&
        assertTrue(Pluralize.pluralize("rave") == "raves") &&
        assertTrue(Pluralize.pluralize("scarf") == "scarves") &&
        assertTrue(Pluralize.pluralize("sale") == "sales") &&
        assertTrue(Pluralize.pluralize("sail") == "sails") &&
        assertTrue(Pluralize.pluralize("swerve") == "swerves")
      },
      test("pluralize 5") {
        assertTrue(Pluralize.pluralize("love") == "loves") &&
        assertTrue(Pluralize.pluralize("dove") == "doves") &&
        assertTrue(Pluralize.pluralize("glove") == "gloves") &&
        assertTrue(Pluralize.pluralize("wharf") == "wharves") &&
        assertTrue(Pluralize.pluralize("valve") == "valves") &&
        assertTrue(Pluralize.pluralize("werewolf") == "werewolves") &&
        assertTrue(Pluralize.pluralize("view") == "views") &&
        assertTrue(Pluralize.pluralize("emu") == "emus") &&
        assertTrue(Pluralize.pluralize("menu") == "menus") &&
        assertTrue(Pluralize.pluralize("wax") == "waxes") &&
        assertTrue(Pluralize.pluralize("fax") == "faxes") &&
        assertTrue(Pluralize.pluralize("nut") == "nuts") &&
        assertTrue(Pluralize.pluralize("crust") == "crusts") &&
        assertTrue(Pluralize.pluralize("lemma") == "lemmata") &&
        assertTrue(Pluralize.pluralize("anathema") == "anathemata") &&
        assertTrue(Pluralize.pluralize("analysis") == "analyses") &&
        assertTrue(Pluralize.pluralize("locus") == "loci") &&
        assertTrue(Pluralize.pluralize("uterus") == "uteri") &&
        assertTrue(Pluralize.pluralize("curriculum") == "curricula") &&
        assertTrue(Pluralize.pluralize("quorum") == "quora") &&
        assertTrue(Pluralize.pluralize("genius") == "geniuses") &&
        assertTrue(Pluralize.pluralize("flower") == "flowers") &&
        assertTrue(Pluralize.pluralize("crash") == "crashes") &&
        assertTrue(Pluralize.pluralize("soul") == "souls") &&
        assertTrue(Pluralize.pluralize("career") == "careers") &&
        assertTrue(Pluralize.pluralize("planet") == "planets") &&
        assertTrue(Pluralize.pluralize("son") == "sons") &&
        assertTrue(Pluralize.pluralize("sun") == "suns") &&
        assertTrue(Pluralize.pluralize("drink") == "drinks") &&
        assertTrue(Pluralize.pluralize("diploma") == "diplomas") &&
        assertTrue(Pluralize.pluralize("dilemma") == "dilemmas") &&
        assertTrue(Pluralize.pluralize("grandma") == "grandmas") &&
        assertTrue(Pluralize.pluralize("no") == "nos") &&
        assertTrue(Pluralize.pluralize("yes") == "yeses") &&
        assertTrue(Pluralize.pluralize("employ") == "employs") &&
        assertTrue(Pluralize.pluralize("employee") == "employees") &&
        assertTrue(Pluralize.pluralize("history") == "histories") &&
        assertTrue(Pluralize.pluralize("story") == "stories") &&
        assertTrue(Pluralize.pluralize("purchase") == "purchases") &&
        assertTrue(Pluralize.pluralize("order") == "orders") &&
        assertTrue(Pluralize.pluralize("key") == "keys") &&
        assertTrue(Pluralize.pluralize("bomb") == "bombs") &&
        assertTrue(Pluralize.pluralize("city") == "cities") &&
        assertTrue(Pluralize.pluralize("sanity") == "sanities") &&
        assertTrue(Pluralize.pluralize("ability") == "abilities") &&
        assertTrue(Pluralize.pluralize("activity") == "activities") &&
        assertTrue(Pluralize.pluralize("cutie") == "cuties") &&
        assertTrue(Pluralize.pluralize("validation") == "validations") &&
        assertTrue(Pluralize.pluralize("floaty") == "floaties") &&
        assertTrue(Pluralize.pluralize("nicety") == "niceties") &&
        assertTrue(Pluralize.pluralize("goalie") == "goalies") &&
        assertTrue(Pluralize.pluralize("crawly") == "crawlies") &&
        assertTrue(Pluralize.pluralize("duty") == "duties") &&
        assertTrue(Pluralize.pluralize("scrutiny") == "scrutinies") &&
        assertTrue(Pluralize.pluralize("deputy") == "deputies") &&
        assertTrue(Pluralize.pluralize("beauty") == "beauties") &&
        assertTrue(Pluralize.pluralize("bank") == "banks") &&
        assertTrue(Pluralize.pluralize("family") == "families") &&
        assertTrue(Pluralize.pluralize("tally") == "tallies") &&
        assertTrue(Pluralize.pluralize("ally") == "allies") &&
        assertTrue(Pluralize.pluralize("alley") == "alleys") &&
        assertTrue(Pluralize.pluralize("valley") == "valleys") &&
        assertTrue(Pluralize.pluralize("medley") == "medleys") &&
        assertTrue(Pluralize.pluralize("melody") == "melodies") &&
        assertTrue(Pluralize.pluralize("trolly") == "trollies") &&
        assertTrue(Pluralize.pluralize("thunk") == "thunks") &&
        assertTrue(Pluralize.pluralize("koala") == "koalas") &&
        assertTrue(Pluralize.pluralize("special") == "specials") &&
        assertTrue(Pluralize.pluralize("book") == "books") &&
        assertTrue(Pluralize.pluralize("knob") == "knobs") &&
        assertTrue(Pluralize.pluralize("crab") == "crabs") &&
        assertTrue(Pluralize.pluralize("plough") == "ploughs") &&
        assertTrue(Pluralize.pluralize("high") == "highs") &&
        assertTrue(Pluralize.pluralize("low") == "lows") &&
        assertTrue(Pluralize.pluralize("hiccup") == "hiccups") &&
        assertTrue(Pluralize.pluralize("bonus") == "bonuses") &&
        assertTrue(Pluralize.pluralize("circus") == "circuses") &&
        assertTrue(Pluralize.pluralize("abacus") == "abacuses") &&
        assertTrue(Pluralize.pluralize("phobia") == "phobias") &&
        assertTrue(Pluralize.pluralize("case") == "cases") &&
        assertTrue(Pluralize.pluralize("lace") == "laces") &&
        assertTrue(Pluralize.pluralize("trace") == "traces") &&
        assertTrue(Pluralize.pluralize("mage") == "mages") &&
        assertTrue(Pluralize.pluralize("lotus") == "lotuses") &&
        assertTrue(Pluralize.pluralize("motorbus") == "motorbuses") &&
        assertTrue(Pluralize.pluralize("cutlas") == "cutlases") &&
        assertTrue(Pluralize.pluralize("tequila") == "tequilas") &&
        assertTrue(Pluralize.pluralize("liar") == "liars") &&
        assertTrue(Pluralize.pluralize("delta") == "deltas")
      },
      test("pluralize 6") {
        assertTrue(Pluralize.pluralize("visa") == "visas") &&
        assertTrue(Pluralize.pluralize("flea") == "fleas") &&
        assertTrue(Pluralize.pluralize("favela") == "favelas") &&
        assertTrue(Pluralize.pluralize("cobra") == "cobras") &&
        assertTrue(Pluralize.pluralize("finish") == "finishes") &&
        assertTrue(Pluralize.pluralize("gorilla") == "gorillas") &&
        assertTrue(Pluralize.pluralize("mass") == "masses") &&
        assertTrue(Pluralize.pluralize("face") == "faces") &&
        assertTrue(Pluralize.pluralize("rabbit") == "rabbits") &&
        assertTrue(Pluralize.pluralize("adventure") == "adventures") &&
        assertTrue(Pluralize.pluralize("breeze") == "breezes") &&
        assertTrue(Pluralize.pluralize("brew") == "brews") &&
        assertTrue(Pluralize.pluralize("canopy") == "canopies") &&
        assertTrue(Pluralize.pluralize("copy") == "copies") &&
        assertTrue(Pluralize.pluralize("spy") == "spies") &&
        assertTrue(Pluralize.pluralize("cave") == "caves") &&
        assertTrue(Pluralize.pluralize("charge") == "charges") &&
        assertTrue(Pluralize.pluralize("cinema") == "cinemas") &&
        assertTrue(Pluralize.pluralize("coffee") == "coffees") &&
        assertTrue(Pluralize.pluralize("favourite") == "favourites") &&
        assertTrue(Pluralize.pluralize("themself") == "themselves") &&
        assertTrue(Pluralize.pluralize("country") == "countries") &&
        assertTrue(Pluralize.pluralize("issue") == "issues") &&
        assertTrue(Pluralize.pluralize("authority") == "authorities") &&
        assertTrue(Pluralize.pluralize("force") == "forces") &&
        assertTrue(Pluralize.pluralize("objective") == "objectives") &&
        assertTrue(Pluralize.pluralize("present") == "presents") &&
        assertTrue(Pluralize.pluralize("industry") == "industries") &&
        assertTrue(Pluralize.pluralize("believe") == "believes") &&
        assertTrue(Pluralize.pluralize("century") == "centuries") &&
        assertTrue(Pluralize.pluralize("category") == "categories") &&
        assertTrue(Pluralize.pluralize("eve") == "eves") &&
        assertTrue(Pluralize.pluralize("fee") == "fees") &&
        assertTrue(Pluralize.pluralize("gene") == "genes") &&
        assertTrue(Pluralize.pluralize("try") == "tries") &&
        assertTrue(Pluralize.pluralize("currency") == "currencies") &&
        assertTrue(Pluralize.pluralize("pose") == "poses") &&
        assertTrue(Pluralize.pluralize("cheese") == "cheeses") &&
        assertTrue(Pluralize.pluralize("clue") == "clues") &&
        assertTrue(Pluralize.pluralize("cheer") == "cheers") &&
        assertTrue(Pluralize.pluralize("litre") == "litres") &&
        assertTrue(Pluralize.pluralize("money") == "monies") &&
        assertTrue(Pluralize.pluralize("attorney") == "attorneys") &&
        assertTrue(Pluralize.pluralize("balcony") == "balconies") &&
        assertTrue(Pluralize.pluralize("cockney") == "cockneys") &&
        assertTrue(Pluralize.pluralize("donkey") == "donkeys") &&
        assertTrue(Pluralize.pluralize("honey") == "honeys") &&
        assertTrue(Pluralize.pluralize("smiley") == "smilies") &&
        assertTrue(Pluralize.pluralize("survey") == "surveys") &&
        assertTrue(Pluralize.pluralize("whiskey") == "whiskeys") &&
        assertTrue(Pluralize.pluralize("whisky") == "whiskies") &&
        assertTrue(Pluralize.pluralize("volley") == "volleys") &&
        assertTrue(Pluralize.pluralize("tongue") == "tongues") &&
        assertTrue(Pluralize.pluralize("suit") == "suits") &&
        assertTrue(Pluralize.pluralize("suite") == "suites") &&
        assertTrue(Pluralize.pluralize("cruise") == "cruises") &&
        assertTrue(Pluralize.pluralize("eave") == "eaves") &&
        assertTrue(Pluralize.pluralize("consultancy") == "consultancies") &&
        assertTrue(Pluralize.pluralize("pouch") == "pouches") &&
        assertTrue(Pluralize.pluralize("wallaby") == "wallabies") &&
        assertTrue(Pluralize.pluralize("abyss") == "abysses") &&
        assertTrue(Pluralize.pluralize("weekly") == "weeklies") &&
        assertTrue(Pluralize.pluralize("whistle") == "whistles") &&
        assertTrue(Pluralize.pluralize("utilise") == "utilises") &&
        assertTrue(Pluralize.pluralize("utilize") == "utilizes") &&
        assertTrue(Pluralize.pluralize("mercy") == "mercies") &&
        assertTrue(Pluralize.pluralize("mercenary") == "mercenaries") &&
        assertTrue(Pluralize.pluralize("take") == "takes") &&
        assertTrue(Pluralize.pluralize("flush") == "flushes") &&
        assertTrue(Pluralize.pluralize("gate") == "gates") &&
        assertTrue(Pluralize.pluralize("evolve") == "evolves") &&
        assertTrue(Pluralize.pluralize("slave") == "slaves") &&
        assertTrue(Pluralize.pluralize("native") == "natives") &&
        assertTrue(Pluralize.pluralize("revolve") == "revolves") &&
        assertTrue(Pluralize.pluralize("twelve") == "twelves") &&
        assertTrue(Pluralize.pluralize("sleeve") == "sleeves") &&
        assertTrue(Pluralize.pluralize("subjective") == "subjectives") &&
        assertTrue(Pluralize.pluralize("stream") == "streams") &&
        assertTrue(Pluralize.pluralize("beam") == "beams") &&
        assertTrue(Pluralize.pluralize("foam") == "foams") &&
        assertTrue(Pluralize.pluralize("callus") == "calluses")
      },
      test("pluralize 7") {
        assertTrue(Pluralize.pluralize("use") == "uses") &&
        assertTrue(Pluralize.pluralize("beau") == "beaus") &&
        assertTrue(Pluralize.pluralize("gateau") == "gateaus") &&
        assertTrue(Pluralize.pluralize("fetus") == "fetuses") &&
        assertTrue(Pluralize.pluralize("luau") == "luaus") &&
        assertTrue(Pluralize.pluralize("pilau") == "pilaus") &&
        assertTrue(Pluralize.pluralize("shoe") == "shoes") &&
        assertTrue(Pluralize.pluralize("sandshoe") == "sandshoes") &&
        assertTrue(Pluralize.pluralize("zeus") == "zeuses") &&
        assertTrue(Pluralize.pluralize("nucleus") == "nuclei") &&
        assertTrue(Pluralize.pluralize("sky") == "skies") &&
        assertTrue(Pluralize.pluralize("beach") == "beaches") &&
        assertTrue(Pluralize.pluralize("brush") == "brushes") &&
        assertTrue(Pluralize.pluralize("hoax") == "hoaxes") &&
        assertTrue(Pluralize.pluralize("scratch") == "scratches") &&
        assertTrue(Pluralize.pluralize("nanny") == "nannies") &&
        assertTrue(Pluralize.pluralize("negro") == "negroes") &&
        assertTrue(Pluralize.pluralize("taco") == "tacos") &&
        assertTrue(Pluralize.pluralize("cafe") == "cafes") &&
        assertTrue(Pluralize.pluralize("cave") == "caves") &&
        assertTrue(Pluralize.pluralize("giraffe") == "giraffes") &&
        assertTrue(Pluralize.pluralize("goodwife") == "goodwives") &&
        assertTrue(Pluralize.pluralize("housewife") == "housewives") &&
        assertTrue(Pluralize.pluralize("safe") == "safes") &&
        assertTrue(Pluralize.pluralize("save") == "saves") &&
        assertTrue(Pluralize.pluralize("pocketknife") == "pocketknives") &&
        assertTrue(Pluralize.pluralize("tartufe") == "tartufes") &&
        assertTrue(Pluralize.pluralize("tartuffe") == "tartuffes") &&
        assertTrue(Pluralize.pluralize("truffle") == "truffles") &&
        assertTrue(Pluralize.pluralize("jefe") == "jefes") &&
        assertTrue(Pluralize.pluralize("agrafe") == "agrafes") &&
        assertTrue(Pluralize.pluralize("agraffe") == "agraffes") &&
        assertTrue(Pluralize.pluralize("bouffe") == "bouffes") &&
        assertTrue(Pluralize.pluralize("carafe") == "carafes") &&
        assertTrue(Pluralize.pluralize("chafe") == "chafes") &&
        assertTrue(Pluralize.pluralize("pouffe") == "pouffes") &&
        assertTrue(Pluralize.pluralize("pouf") == "poufs") &&
        assertTrue(Pluralize.pluralize("piaffe") == "piaffes") &&
        assertTrue(Pluralize.pluralize("gaffe") == "gaffes") &&
        assertTrue(Pluralize.pluralize("executive") == "executives") &&
        assertTrue(Pluralize.pluralize("cove") == "coves") &&
        assertTrue(Pluralize.pluralize("dove") == "doves") &&
        assertTrue(Pluralize.pluralize("fave") == "faves") &&
        assertTrue(Pluralize.pluralize("positive") == "positives") &&
        assertTrue(Pluralize.pluralize("solve") == "solves") &&
        assertTrue(Pluralize.pluralize("trove") == "troves") &&
        assertTrue(Pluralize.pluralize("treasure") == "treasures") &&
        assertTrue(Pluralize.pluralize("suave") == "suaves") &&
        assertTrue(Pluralize.pluralize("bluff") == "bluffs") &&
        assertTrue(Pluralize.pluralize("half") == "halves") &&
        assertTrue(Pluralize.pluralize("knockoff") == "knockoffs") &&
        assertTrue(Pluralize.pluralize("handkerchief") == "handkerchiefs") &&
        assertTrue(Pluralize.pluralize("reed") == "reeds") &&
        assertTrue(Pluralize.pluralize("reef") == "reefs") &&
        assertTrue(Pluralize.pluralize("yourself") == "yourselves") &&
        assertTrue(Pluralize.pluralize("sunroof") == "sunroofs") &&
        assertTrue(Pluralize.pluralize("plateau") == "plateaus") &&
        assertTrue(Pluralize.pluralize("radius") == "radii") &&
        assertTrue(Pluralize.pluralize("stratum") == "strata") &&
        assertTrue(Pluralize.pluralize("stratus") == "strati") &&
        assertTrue(Pluralize.pluralize("focus") == "foci") &&
        assertTrue(Pluralize.pluralize("fungus") == "fungi") &&
        assertTrue(Pluralize.pluralize("appendix") == "appendices") &&
        assertTrue(Pluralize.pluralize("cherub") == "cherubim") &&
        assertTrue(Pluralize.pluralize("memo") == "memos") &&
        assertTrue(Pluralize.pluralize("cello") == "cellos") &&
        assertTrue(Pluralize.pluralize("automaton") == "automata") &&
        assertTrue(Pluralize.pluralize("button") == "buttons") &&
        assertTrue(Pluralize.pluralize("crayon") == "crayons") &&
        assertTrue(Pluralize.pluralize("captive") == "captives") &&
        assertTrue(Pluralize.pluralize("abrasive") == "abrasives") &&
        assertTrue(Pluralize.pluralize("archive") == "archives") &&
        assertTrue(Pluralize.pluralize("additive") == "additives") &&
        assertTrue(Pluralize.pluralize("hive") == "hives") &&
        assertTrue(Pluralize.pluralize("beehive") == "beehives") &&
        assertTrue(Pluralize.pluralize("olive") == "olives")
      },
      test("pluralize 8") {
        assertTrue(Pluralize.pluralize("black olive") == "black olives") &&
        assertTrue(Pluralize.pluralize("chive") == "chives") &&
        assertTrue(Pluralize.pluralize("adjective") == "adjectives") &&
        assertTrue(Pluralize.pluralize("cattle drive") == "cattle drives") &&
        assertTrue(Pluralize.pluralize("explosive") == "explosives") &&
        assertTrue(Pluralize.pluralize("executive") == "executives") &&
        assertTrue(Pluralize.pluralize("negative") == "negatives") &&
        assertTrue(Pluralize.pluralize("fugitive") == "fugitives") &&
        assertTrue(Pluralize.pluralize("progressive") == "progressives") &&
        assertTrue(Pluralize.pluralize("laxative") == "laxatives") &&
        assertTrue(Pluralize.pluralize("incentive") == "incentives") &&
        assertTrue(Pluralize.pluralize("genesis") == "geneses") &&
        assertTrue(Pluralize.pluralize("surprise") == "surprises") &&
        assertTrue(Pluralize.pluralize("enterprise") == "enterprises") &&
        assertTrue(Pluralize.pluralize("relative") == "relatives") &&
        assertTrue(Pluralize.pluralize("positive") == "positives") &&
        assertTrue(Pluralize.pluralize("perspective") == "perspectives") &&
        assertTrue(Pluralize.pluralize("superlative") == "superlatives") &&
        assertTrue(Pluralize.pluralize("afterlife") == "afterlives") &&
        assertTrue(Pluralize.pluralize("native") == "natives") &&
        assertTrue(Pluralize.pluralize("detective") == "detectives") &&
        assertTrue(Pluralize.pluralize("collective") == "collectives") &&
        assertTrue(Pluralize.pluralize("lowlife") == "lowlives") &&
        assertTrue(Pluralize.pluralize("low-life") == "low-lives") &&
        assertTrue(Pluralize.pluralize("strife") == "strifes") &&
        assertTrue(Pluralize.pluralize("pony") == "ponies") &&
        assertTrue(Pluralize.pluralize("phony") == "phonies") &&
        assertTrue(Pluralize.pluralize("felony") == "felonies") &&
        assertTrue(Pluralize.pluralize("colony") == "colonies") &&
        assertTrue(Pluralize.pluralize("symphony") == "symphonies") &&
        assertTrue(Pluralize.pluralize("semicolony") == "semicolonies") &&
        assertTrue(Pluralize.pluralize("radiotelephony") == "radiotelephonies") &&
        assertTrue(Pluralize.pluralize("company") == "companies") &&
        assertTrue(Pluralize.pluralize("ceremony") == "ceremonies") &&
        assertTrue(Pluralize.pluralize("carnivore") == "carnivores") &&
        assertTrue(Pluralize.pluralize("emphasis") == "emphases") &&
        assertTrue(Pluralize.pluralize("abuse") == "abuses") &&
        assertTrue(Pluralize.pluralize("ass") == "asses") &&
        assertTrue(Pluralize.pluralize("mile") == "miles") &&
        assertTrue(Pluralize.pluralize("consensus") == "consensuses") &&
        assertTrue(Pluralize.pluralize("coatdress") == "coatdresses") &&
        assertTrue(Pluralize.pluralize("playhouse") == "playhouses") &&
        assertTrue(Pluralize.pluralize("crispness") == "crispnesses") &&
        assertTrue(Pluralize.pluralize("racehorse") == "racehorses") &&
        assertTrue(Pluralize.pluralize("greatness") == "greatnesses") &&
        assertTrue(Pluralize.pluralize("demon") == "demons") &&
        assertTrue(Pluralize.pluralize("lemon") == "lemons") &&
        assertTrue(Pluralize.pluralize("christmas") == "christmases") &&
        assertTrue(Pluralize.pluralize("zymase") == "zymases") &&
        assertTrue(Pluralize.pluralize("amice") == "amices") &&
        assertTrue(Pluralize.pluralize("titmouse") == "titmice") &&
        assertTrue(Pluralize.pluralize("slice") == "slices") &&
        assertTrue(Pluralize.pluralize("base") == "bases")
      },
      test("pluralize 9") {
        assertTrue(Pluralize.pluralize("database") == "databases") &&
        assertTrue(Pluralize.pluralize("rise") == "rises") &&
        assertTrue(Pluralize.pluralize("uprise") == "uprises") &&
        assertTrue(Pluralize.pluralize("size") == "sizes") &&
        assertTrue(Pluralize.pluralize("prize") == "prizes") &&
        assertTrue(Pluralize.pluralize("booby") == "boobies") &&
        assertTrue(Pluralize.pluralize("hobby") == "hobbies") &&
        assertTrue(Pluralize.pluralize("baby") == "babies") &&
        assertTrue(Pluralize.pluralize("cookie") == "cookies") &&
        assertTrue(Pluralize.pluralize("budgie") == "budgies") &&
        assertTrue(Pluralize.pluralize("calorie") == "calories") &&
        assertTrue(Pluralize.pluralize("brownie") == "brownies") &&
        assertTrue(Pluralize.pluralize("lolly") == "lollies") &&
        assertTrue(Pluralize.pluralize("hippie") == "hippies") &&
        assertTrue(Pluralize.pluralize("smoothie") == "smoothies") &&
        assertTrue(Pluralize.pluralize("techie") == "techies") &&
        assertTrue(Pluralize.pluralize("specie") == "species") &&
        assertTrue(Pluralize.pluralize("quickie") == "quickies") &&
        assertTrue(Pluralize.pluralize("pixie") == "pixies") &&
        assertTrue(Pluralize.pluralize("rotisserie") == "rotisseries") &&
        assertTrue(Pluralize.pluralize("porkpie") == "porkpies") &&
        assertTrue(Pluralize.pluralize("newbie") == "newbies") &&
        assertTrue(Pluralize.pluralize("veggie") == "veggies") &&
        assertTrue(Pluralize.pluralize("bourgeoisie") == "bourgeoisies") &&
        assertTrue(Pluralize.pluralize("party") == "parties") &&
        assertTrue(Pluralize.pluralize("apology") == "apologies") &&
        assertTrue(Pluralize.pluralize("ancestry") == "ancestries") &&
        assertTrue(Pluralize.pluralize("anomaly") == "anomalies") &&
        assertTrue(Pluralize.pluralize("anniversary") == "anniversaries") &&
        assertTrue(Pluralize.pluralize("battery") == "batteries") &&
        assertTrue(Pluralize.pluralize("nappy") == "nappies") &&
        assertTrue(Pluralize.pluralize("hanky") == "hankies") &&
        assertTrue(Pluralize.pluralize("junkie") == "junkies") &&
        assertTrue(Pluralize.pluralize("hogtie") == "hogties") &&
        assertTrue(Pluralize.pluralize("footsie") == "footsies") &&
        assertTrue(Pluralize.pluralize("curry") == "curries") &&
        assertTrue(Pluralize.pluralize("fantasy") == "fantasies") &&
        assertTrue(Pluralize.pluralize("housefly") == "houseflies") &&
        assertTrue(Pluralize.pluralize("falsy") == "falsies") &&
        assertTrue(Pluralize.pluralize("doggy") == "doggies") &&
        assertTrue(Pluralize.pluralize("carny") == "carnies") &&
        assertTrue(Pluralize.pluralize("cabby") == "cabbies") &&
        assertTrue(Pluralize.pluralize("charlie") == "charlies") &&
        assertTrue(Pluralize.pluralize("bookie") == "bookies") &&
        assertTrue(Pluralize.pluralize("auntie") == "aunties")
      }
    )
}
