addSbtPlugin("com.dwijnand"              % "sbt-dynver"   % "4.0.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"    % "1.3.5")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.2.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.9")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"     % "2.0.2")
