name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -XX:+UseG1GC -Xmx4g -Xss4M
  JVM_OPTS: -XX:+PrintCommandLineFlags -XX:+UseG1GC -Xmx4g -Xss4M
  
on:
  pull_request:
  push:
    branches: ['master']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'sbt'
      - name: Lint code
        run: sbt check

  publishLocal:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 8 # ensure it works on 8 because we publish for 8
          cache: 'sbt'
      - name: Check that building packages works
        run: ./sbt +publishLocal

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.12.*', '2.13.*']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'sbt'
      - name: Run tests
        run: sbt ++${{ matrix.scala }} test

  website:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'sbt'
      - name: Check Document Generation
        run: sbt docs/compileDocs

  ci:
    runs-on: ubuntu-20.04
    needs: [ lint, publishLocal, test, website ]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"

  publish:
    runs-on: ubuntu-20.04
    needs: [ ci ]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 8 # ensure it works on 8 because we publish for 8
          cache: 'sbt'
      - name: Release artifacts
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
